/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class model_ScheduleModel */

#ifndef _Included_model_ScheduleModel
#define _Included_model_ScheduleModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     model_ScheduleModel
 * Method:    getSchedule
 * Signature: (Ljava/lang/String;Ljava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_model_ScheduleModel_getSchedule
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
