/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class model_ScheduleModel */

#ifndef _Included_model_ScheduleModel
#define _Included_model_ScheduleModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     model_ScheduleModel
 * Method:    makespan
 * Signature: (Lmodel/Schedule;)J
 */
JNIEXPORT jlong JNICALL Java_model_ScheduleModel_makespan
  (JNIEnv *, jobject, jobject);

/*
 * Class:     model_ScheduleModel
 * Method:    SumWjCj
 * Signature: (Lmodel/Schedule;)J
 */
JNIEXPORT jlong JNICALL Java_model_ScheduleModel_SumWjCj
  (JNIEnv *, jobject, jobject);

/*
 * Class:     model_ScheduleModel
 * Method:    SumWjFj
 * Signature: (Lmodel/Schedule;)J
 */
JNIEXPORT jlong JNICALL Java_model_ScheduleModel_SumWjFj
  (JNIEnv *, jobject, jobject);

/*
 * Class:     model_ScheduleModel
 * Method:    SumWjTj
 * Signature: (Lmodel/Schedule;)J
 */
JNIEXPORT jlong JNICALL Java_model_ScheduleModel_SumWjTj
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
